---

- name: touch foobar
  hosts: foo
  tasks:
    - file:
        path: /home/felixsch/foobar.conf
        state: touch
        mode: "u=rw,g=r,o=r"

- name: touch foobar
  hosts: bar
  tasks:
    - file:
        path: /etc/{{ bar_file }}
        state: touch
        mode: "u=rw,g=r,o=r"
